sudo: false

language: node_js

node_js:
  - 12

cache:
  directories:
    - ~/.npm

notifications:
  email: false

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      script: npm test
    - stage: npm release
      if: branch = master
      node_js: 12
      script: npm run semantic-release